name: CI

on:
  push:
    branches:
    - master
    - release/*
    - feature

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16.16.0'
    - run: npm install
    - run: npm run build:prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        apiKey: ${{ secrets.FIREBASE_API_KEY }},
        authDomain: ${{ secrets.FIREBASE_AUTH_DOMAIN }},
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }},
        storageBucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }},
        messagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }},
        appId: ${{ secrets.FIREBASE_APP_ID }}
